# Generated by Django 4.2.13 on 2024-05-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(blank=True, max_length=255, null=True)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('hidden', models.BooleanField(default=False)),
                ('size_vertical', models.FloatField()),
                ('size_horizontal', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
