# Generated by Django 4.2.13 on 2024-07-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='partial_cycle1',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='partial_cycle2',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='partial_cycle3',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='zindex',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='zindex',
        ),
        migrations.AddField(
            model_name='bar',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='detail_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bar',
            field=models.ForeignKey(blank=True, db_column='bar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.bar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.task'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.IntegerField(unique=True)),
                ('bar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer', to='lists.bar')),
                ('list', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer', to='lists.tasklist')),
            ],
            options={
                'db_table': 'layers',
            },
        ),
    ]
