# Generated by Django 4.2.13 on 2024-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_tasklist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='size_horizontal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='size_vertical',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='x_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='y_axis',
            field=models.FloatField(default=0),
        ),
    ]
